### ISSUE TITLE
Property for failed residue mapping

### ISSUE THREAD

**Issue by ReneRanzinger** [CCRC-will/glycoTree#1]
Currently for each residue an object with information is returned by the web service:
```
{
            "residue_id": "N50",
            "name": "Gal",
            "anomer": "a",
            "absolute": "D",
            "ring": "p",
            "parent_id": "N6",
            "site": "3",
            "form_name": "Galp",
            "glycoct_index": "17",
            "residue_name": "N-glycan_a-D-Galp_50",
            "notes": "validated by Qrator",
            "enzymes": null
}
```

There are two indirect ways of detecting if a residue could not be mapped to the selected glycotree:
* _residue_id_ is a number rather than an alphanumerical string
* _notes_ contains "validated by Qrator"

My concern is that especially the later might not be true if new residues have been curated outside the Qrator application. I would prefer to have an explicit property in the JSON object that indicates if the residue could be mapped to the tree or not. For example:
```
{
            "residue_id": "N50",
            "mapped": "yes",
            ...
}
```
or
```
{
            "residue_id": "N50",
            "glytoctree": "N glycan glyco tree",
            ...
}
```

**Comment by CCRC-will** [comment]
The 'residues' object property 'residue_name' specifies the semantics of mapping, i.e., the full name of the canonical residue to which  the residue is mapped), and thus provides explicit information about mapping.

To facilitate data processing, an new object property 'glycotree' was implemented by exploding the value of 'residue_name'. The property 'glycotree' contains the name of the glycotree if the residue is mapped to a glycotree and the string 'none' if it is not.
