### ISSUE TITLE
glycoct_index missing for non mapped residue

### ISSUE THREAD

**Issue by ReneRanzinger** [CCRC-will/glycoTree#10]
Currently the _glycoct_index_ property for residues is only shown for mapped residues but not for unmapped residues. The index is used as _residues_id_ instead. It would still be preferable to have the _glycoct_index_ property present all the time.

**Comment by ReneRanzinger** [comment]
I looked into it some more. It seems that if the structures is partially mapped (only some residues can not be mapped) the index is there. However, if the mapping fails entirely (e.g. map an N-Glycan to the O-Glycan tree) the index is missing. If its hard to do we can neglect this case since the error property will have a message about the failing. In that case just go ahead and close the ticket.

**Comment by CCRC-will** [comment]
When TreeBuilder (java) fails to map any residue, the initial csv encoding with no mapping is used to create residue arrays.  These arrays do not contain a glycoct_index attribute (normally set by TreeBuilder). This is now detected by checkers.php and the glycoct_index is added and set to the same value as residue_id.
