### ISSUE TITLE
Error message in case of invalid input

### ISSUE THREAD

**Issue by ReneRanzinger** [CCRC-will/glycoTree#4]
There are multiple reasons the web service call might fail due to invalid input:
* _glycoct_ is missing
* GlycoCT sequence is invalid
* _type_ is missing
* GlycoTree type is not valid

In all cases the webservice responds with:
```
{
"residues": null
}
```
I would prefer to have a top level property that returns errors that can help fixing this problem. E.g.,
```
{
   "error":[
      {
         "type":"input error",
         "message":"Parameter type missing"
      },
      {
         "type":"sequence error",
         "message":"Found 'ABC' was expecting 'RES' in GlycoCT sequence."
      },
      {
         "type":"input error",
         "message":"'ABC' is not a valid GlycoTree type"
      }
   ],
   "residues":null
}
```
The _error_ property would be absent of an empty array if no error occurred.

**Comment by CCRC-will** [comment]
Fix: modify TreeBuilder4 such that it accepts minimum number of matched residues as zero ("-n 0").

**Comment by CCRC-will** [comment]
Fixed - may require implementation of additional error messages, as requested.
